In [7]:
import numpy as np

numpy array

In [3]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
#2d array
twoD_arr=np.array([[1,2],[3,4],[5,6],[7,8]])
print(twoD_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


creating a structured data type and apply to ndarray object

In [6]:
dt=np.dtype([('age',np.int8)])

In [8]:
a=np.array([(10),(20),(30)],dtype=dt)
print(a['age'])

[10 20 30]


In [15]:
student=np.dtype([('name','S20'),('age','i8'),('marks','f4')])
print(student)

[('name', 'S20'), ('age', '<i8'), ('marks', '<f4')]


In [17]:
arr1=np.array([('gokul',21,50),('adwaith',21,50)],dtype=student)
print(arr1)

[(b'gokul', 21, 50.) (b'adwaith', 21, 50.)]


Array Attributes


1. ndarray.shape

In [18]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


2. ndarray.ndim   
This array attribute returns the number of array dimensions

In [19]:
print(a.ndim)

2


3. numpy.itemsize
This array attribute returns the length Of each element of array in bytes.

In [20]:
print(a.itemsize)

8


Array Creation Routines


1. numpy.zeros

In [21]:
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [22]:
x=np.zeros([2,2] ,dtype='int8')
print(x)

[[0 0]
 [0 0]]


2. numpy.ones

In [23]:
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [25]:
x=np.ones([4,4] ,dtype='int8')
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


3. numpy.fromiter
This function builds an ndarray object from any iterable object. A new
one-dimensional array is returned by this function

In [ ]:
# Obtain iterator object from list

my_list =range(5)
it=iter(my_list)

In [27]:
# use iterator to create ndarray
x = np.fromiter(it, dtype = float)
print(x)


[0. 1. 2. 3. 4.]


Array from Numerical Ranges


1. numpy.arange

In [28]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [29]:
x = np.arange(5,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [30]:
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


2. numpy.linspace

In [31]:
x=np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [32]:
# endpoint set to false
x=np.linspace(10,20,5, endpoint=False)
print(x)

[10. 12. 14. 16. 18.]


In [33]:
# find retstep value
x=np.linspace(10,20,5, retstep=True)
print(x)

(array([10. , 12.5, 15. , 17.5, 20. ]), np.float64(2.5))


Indexing & Slicing

In [35]:
a = np.arange(10)
print(a)
s = slice(2,7,2)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [37]:
a = np.arange(10)
print(a)
b = a[2:7:2]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [38]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print(a[1:])

[[4 5 6]
 [7 8 9]]


a[row, column]

a[1, ...]  → row 1, all columns
a[..., 1]  → all rows, column 1

In [40]:
#array of items in second column
print(a[...,1])

[2 5 8]


In [41]:
#array of items in second row
print(a[1,...])

[4 5 6]


In [42]:
#array of items from column two onwards
print(a[...,1:])

[[2 3]
 [5 6]
 [8 9]]


Advanced Indexing
There are two types of advanced indexing - Integer and Boolean.


Integer Indexing

In [43]:
arr1=np.array([[1,2],[3,4],[5,6]])
print(arr1)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(arr1[[0,1,2],[0,1,0]])
#The selection includes elements at (0,0), (1 , 1) and (2,0) from the first array.

[1 4 5]


In [ ]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#corner elements
rows=np.array([[0,0],[3,3]])
cols=np.array([[0,2],[0,2]])
y=x[rows,cols]
print(y)

[[ 0  2]
 [ 9 11]]


rows       cols       coordinate       value

  0          0          (0,0)    →       0
  0          2          (0,2)    →       2

  3          0          (3,0)    →       9
  3          2          (3,2)    →      11

Boolean Array Indexing

In [47]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [48]:
print(x[x>5])

[ 6  7  8  9 10 11]
