In [1]:
import numpy as np

In [4]:
arr=np.array([i for i in range(1,150) if i%3==0 and i%5==0])

In [8]:
print(arr)
arr=arr.reshape(3,3)
print(arr)

[ 15  30  45  60  75  90 105 120 135]
[[ 15  30  45]
 [ 60  75  90]
 [105 120 135]]


In [12]:
arr1=arr[[0,1,1,2],[1,0,2,1]]
print(arr1)


[ 30  60  90 120]


In [14]:
arr2=np.arange(15,140,15).reshape(3,3)
print(arr2)

[[ 15  30  45]
 [ 60  75  90]
 [105 120 135]]


In [15]:
a=arr2[[0,1,1,2],[1,0,2,1]]
print(a)

[ 30  60  90 120]


In [17]:
arr3=np.arange(5,50,5)
arr4=np.multiply(arr,3)
arr4=arr4.reshape(3,3)
print(arr4)

[[ 45  90 135]
 [180 225 270]
 [315 360 405]]
